name: Generate Snake and Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 1. Pobranie repozytorium (wymagane dla tej akcji statystyk)
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2. Generowanie węża
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: DawidWawrzeniuk
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. PRAWIDŁOWE generowanie statystyk jako pliki SVG
      - name: Generate GitHub Stats
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: dist
          theme: visual_studio_dark

      # 4. Wypchnięcie wszystkich plików (wąż + statystyki) do gałęzi "output"
      - name: push files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
